Added command fcrdns

diff --git a/esp b/esp
--- a/esp
+++ b/esp
@@ -127,10 +127,13 @@ function check_backups () {
 
 # Check to see if easyapache is found in the process list
 function check_easyapache () {
-    ps auxf | grep easyapache | grep -v grep > /dev/null;
-    if [ $? -eq 0 ]; then
-        display_warn "easyapache";
+    if [ -f /usr/local/apache/AN_EASYAPACHE_BUILD_IS_CURRENTLY_RUNNING ]; then
+        ps auxf | grep easyapache | grep -v grep > /dev/null;
+        if [ $? -eq 0 ]; then
+            display_warn "easyapache";
+        fi;
     fi;
+
 };
 
 # This check will verify if apache is up and the server status page is found
@@ -267,11 +270,37 @@ alias lsip='ifconfig | grep "inet addr"| grep -v "127.0.0.1"';
 alias lsip-real="curl -s http://cpanel.net/showip.cgi";
 alias lsip-mainip="strings /var/cpanel/mainip";
 
+function fcrdns() {
+   if [ -n "$1" ]; then
+       esp_fcdns_check "$1";
+    else
+       for IP in `echo \`cat /var/cpanel/mainip\`&&cat /etc/ips|awk {{print\ $1}}|cut -d \\: -f 1`; do
+           esp_fcdns_check "$IP";
+       done
+   fi
+}
+function esp_fcdns_check() {
+   local ip_to_check="$1";
+   local rdns="`dig @4.2.2.2 +short -x $ip_to_check`";
+   if [ -z $rdns ]; then
+       local rdns="Failed";
+       local rdns_ip="Failed";
+   else
+       local rdns_ip="`dig @4.2.2.2 +short -x $ip_to_check | xargs dig +short `";
+   fi
+   if [ "$ip_to_check" = "$rdns_ip" ]; then
+       echo "$(tput setaf 3)$ip_to_check$(tput setaf 2) PASSED FCrDNS valadation $(tput sgr0)$ip_to_check$(tput setaf 3)->$(tput sgr0)$rdns$(tput setaf 3)->$(tput sgr0)$rdns_ip";
+   else
+       echo "$(tput setaf 3)$ip_to_check$(tput setaf 1) FAILED FCrDNS validation $(tput sgr0)$ip_to_check$(tput setaf 3)->$(tput sgr0)$rdns$(tput setaf 3)->$(tput sgr0)$rdns_ip";
+   fi
+}
+
 function cphelp_net() {
     help_section "Network Information";
         help_command "lsip" "Displays all the ip addresses in ifconfig, without the thrills";
         help_command "lsip-real" "Displays the external ip address of the server seen by the internet.";
         help_command "lsip-mainip" "Displays cPanel's mainip from /v/c/mainip";
+        help_command "fcrdns" "Checks the rDNS and Forward-confirmed reverse DNS of all IPs, or an IP you specify";
 }
 
 
@@ -427,7 +456,7 @@ function PS1_Alerts() {
 	echo -ne `check_yum``check_mailserver``check_easyapache``check_upcp``check_backups``check_apache``new_connected``check_exim``check_mysql`;
 }
 
-export PS1="\n$(tput sgr0)[\H | $IP_ADDR] \e[0;36mAlerts: \`PS1_Alerts\`\n\[\033[0;33m\][$TICKET]\`if [[ \$? = "0" ]]; then echo "\\[\\033[32m\\]"; else echo "\\[\\033[31m\\]"; fi\` [\`if [[ `pwd|wc -c|tr -d " "` > 18 ]]; then echo "\\w"; else echo "\\w"; fi\`]\$\[\033[0m\] "; echo -ne "\033]0;`hostname -s`:`pwd`\007";
+export PS1="\n$(tput setaf 7)[$(tput setaf 3)\H$(tput setaf 7)|$(tput setaf 3)$IP_ADDR$(tput setaf 7)] $(tput setaf 6)Alerts: \`PS1_Alerts\`\n$(tput setaf 7)[$(tput setaf 3)$TICKET$(tput setaf 7)]\`if [[ \$? = "0" ]]; then echo "\\[\\033[32m\\]"; else echo "\\[\\033[31m\\]"; fi\` [\`if [[ `pwd|wc -c|tr -d " "` > 18 ]]; then echo "\\w"; else echo "\\w"; fi\`]\$\[\033[0m\] "; echo -ne "\033]0;`hostname -s`:`pwd`\007";
 
 save_connected;
 if [ "$ssp" == "1" ]; then
